stages:
  - build
  - test
  - deploy

variables:
  APP_REPO: "gitlab.com/cjbarker/pyhack"

build:
  image: registry.${APP_REPO}:latest
  stage: build
  script:
    - pipenv sync
    - pipenv run pylint pyhack -d W --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'

test:
  image: registry.${APP_REPO}:latest
  stage: test
  script:
    - coverage erase
    - coverage run --source pyhack -m nose2
    # needed for CI badge to grab
    - coverage report
    # produce for hosting report
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 2 weeks

pages:
  image: registry.${APP_REPO}:latest
  stage: deploy
  script:
    # update pages with latest coverage report
    - cd ${CI_PROJECT_DIR}
    - mkdir -p .public/docs
    - cp -R htmlcov/* .public
    # create docs
    - cd docs
    - make clean
    - make html
    - cp -R _build/html/* ../.public/docs
    - cd ..
    # enable live
    - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 30 days
  only:
    - master
